/*
 * Cloudflare API
 * Interact with Cloudflare's products and services via the Cloudflare API. For more information on how to create and troubleshoot API tokens, refer to our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).  Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * ActionParametersSetCacheSettingsCacheKeyCustomKeyCookie
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-22T14:44:19.166727222+09:00[Asia/Tokyo]")
public class ActionParametersSetCacheSettingsCacheKeyCustomKeyCookie {
  @SerializedName("check_presence")
  private List<Object> checkPresence = null;

  @SerializedName("include")
  private List<Object> include = null;

  public ActionParametersSetCacheSettingsCacheKeyCustomKeyCookie checkPresence(List<Object> checkPresence) {
    this.checkPresence = checkPresence;
    return this;
  }

  public ActionParametersSetCacheSettingsCacheKeyCustomKeyCookie addCheckPresenceItem(Object checkPresenceItem) {
    if (this.checkPresence == null) {
      this.checkPresence = new ArrayList<Object>();
    }
    this.checkPresence.add(checkPresenceItem);
    return this;
  }

   /**
   * Get checkPresence
   * @return checkPresence
  **/
  @Schema(example = "[\"cookie_1\"]", description = "")
  public List<Object> getCheckPresence() {
    return checkPresence;
  }

  public void setCheckPresence(List<Object> checkPresence) {
    this.checkPresence = checkPresence;
  }

  public ActionParametersSetCacheSettingsCacheKeyCustomKeyCookie include(List<Object> include) {
    this.include = include;
    return this;
  }

  public ActionParametersSetCacheSettingsCacheKeyCustomKeyCookie addIncludeItem(Object includeItem) {
    if (this.include == null) {
      this.include = new ArrayList<Object>();
    }
    this.include.add(includeItem);
    return this;
  }

   /**
   * Get include
   * @return include
  **/
  @Schema(example = "[\"cookie1\"]", description = "")
  public List<Object> getInclude() {
    return include;
  }

  public void setInclude(List<Object> include) {
    this.include = include;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionParametersSetCacheSettingsCacheKeyCustomKeyCookie actionParametersSetCacheSettingsCacheKeyCustomKeyCookie = (ActionParametersSetCacheSettingsCacheKeyCustomKeyCookie) o;
    return Objects.equals(this.checkPresence, actionParametersSetCacheSettingsCacheKeyCustomKeyCookie.checkPresence) &&
        Objects.equals(this.include, actionParametersSetCacheSettingsCacheKeyCustomKeyCookie.include);
  }

  @Override
  public int hashCode() {
    return Objects.hash(checkPresence, include);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionParametersSetCacheSettingsCacheKeyCustomKeyCookie {\n");
    
    sb.append("    checkPresence: ").append(toIndentedString(checkPresence)).append("\n");
    sb.append("    include: ").append(toIndentedString(include)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
