/*
 * Cloudflare API
 * Interact with Cloudflare's products and services via the Cloudflare API. For more information on how to create and troubleshoot API tokens, refer to our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).  Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.DnsSecondaryPrimaryZoneComponentsSchemasIdentifier;
import io.swagger.client.model.Peers;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * CloudflareClientAPISingleRequestOutgoing
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-22T14:44:19.166727222+09:00[Asia/Tokyo]")
public class CloudflareClientAPISingleRequestOutgoing {
  @SerializedName("id")
  private DnsSecondaryPrimaryZoneComponentsSchemasIdentifier id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("peers")
  private Peers peers = null;

  public CloudflareClientAPISingleRequestOutgoing id(DnsSecondaryPrimaryZoneComponentsSchemasIdentifier id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(required = true, description = "")
  public DnsSecondaryPrimaryZoneComponentsSchemasIdentifier getId() {
    return id;
  }

  public void setId(DnsSecondaryPrimaryZoneComponentsSchemasIdentifier id) {
    this.id = id;
  }

  public CloudflareClientAPISingleRequestOutgoing name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @Schema(required = true, description = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CloudflareClientAPISingleRequestOutgoing peers(Peers peers) {
    this.peers = peers;
    return this;
  }

   /**
   * Get peers
   * @return peers
  **/
  @Schema(required = true, description = "")
  public Peers getPeers() {
    return peers;
  }

  public void setPeers(Peers peers) {
    this.peers = peers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CloudflareClientAPISingleRequestOutgoing cloudflareClientAPISingleRequestOutgoing = (CloudflareClientAPISingleRequestOutgoing) o;
    return Objects.equals(this.id, cloudflareClientAPISingleRequestOutgoing.id) &&
        Objects.equals(this.name, cloudflareClientAPISingleRequestOutgoing.name) &&
        Objects.equals(this.peers, cloudflareClientAPISingleRequestOutgoing.peers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, peers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CloudflareClientAPISingleRequestOutgoing {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    peers: ").append(toIndentedString(peers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
