/*
 * Cloudflare API
 * Interact with Cloudflare's products and services via the Cloudflare API. For more information on how to create and troubleshoot API tokens, refer to our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).  Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * The version of the analyzed script.
 */
@Schema(description = "The version of the analyzed script.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-22T14:44:19.166727222+09:00[Asia/Tokyo]")
public class ComponentsSchemasVersion {
  @SerializedName("fetched_at")
  private String fetchedAt = null;

  @SerializedName("hash")
  private String hash = null;

  @SerializedName("js_integrity_score")
  private Integer jsIntegrityScore = null;

  public ComponentsSchemasVersion fetchedAt(String fetchedAt) {
    this.fetchedAt = fetchedAt;
    return this;
  }

   /**
   * Get fetchedAt
   * @return fetchedAt
  **/
  @Schema(description = "")
  public String getFetchedAt() {
    return fetchedAt;
  }

  public void setFetchedAt(String fetchedAt) {
    this.fetchedAt = fetchedAt;
  }

  public ComponentsSchemasVersion hash(String hash) {
    this.hash = hash;
    return this;
  }

   /**
   * Get hash
   * @return hash
  **/
  @Schema(description = "")
  public String getHash() {
    return hash;
  }

  public void setHash(String hash) {
    this.hash = hash;
  }

  public ComponentsSchemasVersion jsIntegrityScore(Integer jsIntegrityScore) {
    this.jsIntegrityScore = jsIntegrityScore;
    return this;
  }

   /**
   * Get jsIntegrityScore
   * @return jsIntegrityScore
  **/
  @Schema(description = "")
  public Integer getJsIntegrityScore() {
    return jsIntegrityScore;
  }

  public void setJsIntegrityScore(Integer jsIntegrityScore) {
    this.jsIntegrityScore = jsIntegrityScore;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComponentsSchemasVersion componentsSchemasVersion = (ComponentsSchemasVersion) o;
    return Objects.equals(this.fetchedAt, componentsSchemasVersion.fetchedAt) &&
        Objects.equals(this.hash, componentsSchemasVersion.hash) &&
        Objects.equals(this.jsIntegrityScore, componentsSchemasVersion.jsIntegrityScore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(fetchedAt, hash, jsIntegrityScore);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComponentsSchemasVersion {\n");
    
    sb.append("    fetchedAt: ").append(toIndentedString(fetchedAt)).append("\n");
    sb.append("    hash: ").append(toIndentedString(hash)).append("\n");
    sb.append("    jsIntegrityScore: ").append(toIndentedString(jsIntegrityScore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
