/*
 * Cloudflare API
 * Interact with Cloudflare's products and services via the Cloudflare API. For more information on how to create and troubleshoot API tokens, refer to our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).  Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ConsumerSettings;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ConsumerCreated
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-22T14:44:19.166727222+09:00[Asia/Tokyo]")
public class ConsumerCreated {
  @SerializedName("created_on")
  private Object createdOn = null;

  @SerializedName("dead_letter_queue")
  private String deadLetterQueue = null;

  @SerializedName("environment")
  private Object environment = null;

  @SerializedName("queue_name")
  private Object queueName = null;

  @SerializedName("script_name")
  private Object scriptName = null;

  @SerializedName("settings")
  private ConsumerSettings settings = null;

   /**
   * Get createdOn
   * @return createdOn
  **/
  @Schema(description = "")
  public Object getCreatedOn() {
    return createdOn;
  }

  public ConsumerCreated deadLetterQueue(String deadLetterQueue) {
    this.deadLetterQueue = deadLetterQueue;
    return this;
  }

   /**
   * Get deadLetterQueue
   * @return deadLetterQueue
  **/
  @Schema(description = "")
  public String getDeadLetterQueue() {
    return deadLetterQueue;
  }

  public void setDeadLetterQueue(String deadLetterQueue) {
    this.deadLetterQueue = deadLetterQueue;
  }

   /**
   * Get environment
   * @return environment
  **/
  @Schema(description = "")
  public Object getEnvironment() {
    return environment;
  }

   /**
   * Get queueName
   * @return queueName
  **/
  @Schema(description = "")
  public Object getQueueName() {
    return queueName;
  }

   /**
   * Get scriptName
   * @return scriptName
  **/
  @Schema(description = "")
  public Object getScriptName() {
    return scriptName;
  }

  public ConsumerCreated settings(ConsumerSettings settings) {
    this.settings = settings;
    return this;
  }

   /**
   * Get settings
   * @return settings
  **/
  @Schema(description = "")
  public ConsumerSettings getSettings() {
    return settings;
  }

  public void setSettings(ConsumerSettings settings) {
    this.settings = settings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsumerCreated consumerCreated = (ConsumerCreated) o;
    return Objects.equals(this.createdOn, consumerCreated.createdOn) &&
        Objects.equals(this.deadLetterQueue, consumerCreated.deadLetterQueue) &&
        Objects.equals(this.environment, consumerCreated.environment) &&
        Objects.equals(this.queueName, consumerCreated.queueName) &&
        Objects.equals(this.scriptName, consumerCreated.scriptName) &&
        Objects.equals(this.settings, consumerCreated.settings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdOn, deadLetterQueue, environment, queueName, scriptName, settings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsumerCreated {\n");
    
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    sb.append("    deadLetterQueue: ").append(toIndentedString(deadLetterQueue)).append("\n");
    sb.append("    environment: ").append(toIndentedString(environment)).append("\n");
    sb.append("    queueName: ").append(toIndentedString(queueName)).append("\n");
    sb.append("    scriptName: ").append(toIndentedString(scriptName)).append("\n");
    sb.append("    settings: ").append(toIndentedString(settings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
