/*
 * Cloudflare API
 * Interact with Cloudflare's products and services via the Cloudflare API. For more information on how to create and troubleshoot API tokens, refer to our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).  Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * GatewayAccountResult
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-22T14:44:19.166727222+09:00[Asia/Tokyo]")
public class GatewayAccountResult {
  @SerializedName("gateway_tag")
  private String gatewayTag = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("provider_name")
  private String providerName = null;

  public GatewayAccountResult gatewayTag(String gatewayTag) {
    this.gatewayTag = gatewayTag;
    return this;
  }

   /**
   * Get gatewayTag
   * @return gatewayTag
  **/
  @Schema(description = "")
  public String getGatewayTag() {
    return gatewayTag;
  }

  public void setGatewayTag(String gatewayTag) {
    this.gatewayTag = gatewayTag;
  }

  public GatewayAccountResult id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @Schema(description = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public GatewayAccountResult providerName(String providerName) {
    this.providerName = providerName;
    return this;
  }

   /**
   * Get providerName
   * @return providerName
  **/
  @Schema(description = "")
  public String getProviderName() {
    return providerName;
  }

  public void setProviderName(String providerName) {
    this.providerName = providerName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GatewayAccountResult gatewayAccountResult = (GatewayAccountResult) o;
    return Objects.equals(this.gatewayTag, gatewayAccountResult.gatewayTag) &&
        Objects.equals(this.id, gatewayAccountResult.id) &&
        Objects.equals(this.providerName, gatewayAccountResult.providerName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gatewayTag, id, providerName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GatewayAccountResult {\n");
    
    sb.append("    gatewayTag: ").append(toIndentedString(gatewayTag)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    providerName: ").append(toIndentedString(providerName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
