/*
 * Cloudflare API
 * Interact with Cloudflare's products and services via the Cloudflare API. For more information on how to create and troubleshoot API tokens, refer to our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).  Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ApiResponseCommonFailure;
import io.swagger.client.model.CertificateResponseSingle;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse4xx347
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-22T14:44:19.166727222+09:00[Asia/Tokyo]")
public class InlineResponse4xx347 extends CertificateResponseSingle {
  @SerializedName("errors")
  private Object inlineResponse4xx347Errors = null;

  @SerializedName("messages")
  private Object inlineResponse4xx347Messages = null;

  @SerializedName("result")
  private Object inlineResponse4xx347Result = null;

  @SerializedName("success")
  private Boolean inlineResponse4xx347Success = null;

  public InlineResponse4xx347 inlineResponse4xx347Errors(Object inlineResponse4xx347Errors) {
    this.inlineResponse4xx347Errors = inlineResponse4xx347Errors;
    return this;
  }

   /**
   * Get inlineResponse4xx347Errors
   * @return inlineResponse4xx347Errors
  **/
  @Schema(example = "[{\"code\":7003,\"message\":\"No route for the URI\"}]", required = true, description = "")
  public Object getInlineResponse4xx347Errors() {
    return inlineResponse4xx347Errors;
  }

  public void setInlineResponse4xx347Errors(Object inlineResponse4xx347Errors) {
    this.inlineResponse4xx347Errors = inlineResponse4xx347Errors;
  }

  public InlineResponse4xx347 inlineResponse4xx347Messages(Object inlineResponse4xx347Messages) {
    this.inlineResponse4xx347Messages = inlineResponse4xx347Messages;
    return this;
  }

   /**
   * Get inlineResponse4xx347Messages
   * @return inlineResponse4xx347Messages
  **/
  @Schema(example = "[]", required = true, description = "")
  public Object getInlineResponse4xx347Messages() {
    return inlineResponse4xx347Messages;
  }

  public void setInlineResponse4xx347Messages(Object inlineResponse4xx347Messages) {
    this.inlineResponse4xx347Messages = inlineResponse4xx347Messages;
  }

  public InlineResponse4xx347 inlineResponse4xx347Result(Object inlineResponse4xx347Result) {
    this.inlineResponse4xx347Result = inlineResponse4xx347Result;
    return this;
  }

   /**
   * Get inlineResponse4xx347Result
   * @return inlineResponse4xx347Result
  **/
  @Schema(required = true, description = "")
  public Object getInlineResponse4xx347Result() {
    return inlineResponse4xx347Result;
  }

  public void setInlineResponse4xx347Result(Object inlineResponse4xx347Result) {
    this.inlineResponse4xx347Result = inlineResponse4xx347Result;
  }

  public InlineResponse4xx347 inlineResponse4xx347Success(Boolean inlineResponse4xx347Success) {
    this.inlineResponse4xx347Success = inlineResponse4xx347Success;
    return this;
  }

   /**
   * Whether the API call was successful
   * @return inlineResponse4xx347Success
  **/
  @Schema(example = "false", required = true, description = "Whether the API call was successful")
  public Boolean getInlineResponse4xx347Success() {
    return inlineResponse4xx347Success;
  }

  public void setInlineResponse4xx347Success(Boolean inlineResponse4xx347Success) {
    this.inlineResponse4xx347Success = inlineResponse4xx347Success;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse4xx347 inlineResponse4xx347 = (InlineResponse4xx347) o;
    return Objects.equals(this.inlineResponse4xx347Errors, inlineResponse4xx347.inlineResponse4xx347Errors) &&
        Objects.equals(this.inlineResponse4xx347Messages, inlineResponse4xx347.inlineResponse4xx347Messages) &&
        Objects.equals(this.inlineResponse4xx347Result, inlineResponse4xx347.inlineResponse4xx347Result) &&
        Objects.equals(this.inlineResponse4xx347Success, inlineResponse4xx347.inlineResponse4xx347Success) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inlineResponse4xx347Errors, inlineResponse4xx347Messages, inlineResponse4xx347Result, inlineResponse4xx347Success, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse4xx347 {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    inlineResponse4xx347Errors: ").append(toIndentedString(inlineResponse4xx347Errors)).append("\n");
    sb.append("    inlineResponse4xx347Messages: ").append(toIndentedString(inlineResponse4xx347Messages)).append("\n");
    sb.append("    inlineResponse4xx347Result: ").append(toIndentedString(inlineResponse4xx347Result)).append("\n");
    sb.append("    inlineResponse4xx347Success: ").append(toIndentedString(inlineResponse4xx347Success)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
