/*
 * Cloudflare API
 * Interact with Cloudflare's products and services via the Cloudflare API. For more information on how to create and troubleshoot API tokens, refer to our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).  Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ApiResponseCommonFailure;
import io.swagger.client.model.BillingHistoryCollection;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse4xx301
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-22T14:44:19.166727222+09:00[Asia/Tokyo]")
public class InlineResponse4xx301 extends BillingHistoryCollection {
  @SerializedName("errors")
  private Object inlineResponse4xx301Errors = null;

  @SerializedName("messages")
  private Object inlineResponse4xx301Messages = null;

  @SerializedName("result")
  private Object inlineResponse4xx301Result = null;

  @SerializedName("success")
  private Boolean inlineResponse4xx301Success = null;

  public InlineResponse4xx301 inlineResponse4xx301Errors(Object inlineResponse4xx301Errors) {
    this.inlineResponse4xx301Errors = inlineResponse4xx301Errors;
    return this;
  }

   /**
   * Get inlineResponse4xx301Errors
   * @return inlineResponse4xx301Errors
  **/
  @Schema(example = "[{\"code\":7003,\"message\":\"No route for the URI\"}]", required = true, description = "")
  public Object getInlineResponse4xx301Errors() {
    return inlineResponse4xx301Errors;
  }

  public void setInlineResponse4xx301Errors(Object inlineResponse4xx301Errors) {
    this.inlineResponse4xx301Errors = inlineResponse4xx301Errors;
  }

  public InlineResponse4xx301 inlineResponse4xx301Messages(Object inlineResponse4xx301Messages) {
    this.inlineResponse4xx301Messages = inlineResponse4xx301Messages;
    return this;
  }

   /**
   * Get inlineResponse4xx301Messages
   * @return inlineResponse4xx301Messages
  **/
  @Schema(example = "[]", required = true, description = "")
  public Object getInlineResponse4xx301Messages() {
    return inlineResponse4xx301Messages;
  }

  public void setInlineResponse4xx301Messages(Object inlineResponse4xx301Messages) {
    this.inlineResponse4xx301Messages = inlineResponse4xx301Messages;
  }

  public InlineResponse4xx301 inlineResponse4xx301Result(Object inlineResponse4xx301Result) {
    this.inlineResponse4xx301Result = inlineResponse4xx301Result;
    return this;
  }

   /**
   * Get inlineResponse4xx301Result
   * @return inlineResponse4xx301Result
  **/
  @Schema(required = true, description = "")
  public Object getInlineResponse4xx301Result() {
    return inlineResponse4xx301Result;
  }

  public void setInlineResponse4xx301Result(Object inlineResponse4xx301Result) {
    this.inlineResponse4xx301Result = inlineResponse4xx301Result;
  }

  public InlineResponse4xx301 inlineResponse4xx301Success(Boolean inlineResponse4xx301Success) {
    this.inlineResponse4xx301Success = inlineResponse4xx301Success;
    return this;
  }

   /**
   * Whether the API call was successful
   * @return inlineResponse4xx301Success
  **/
  @Schema(example = "false", required = true, description = "Whether the API call was successful")
  public Boolean getInlineResponse4xx301Success() {
    return inlineResponse4xx301Success;
  }

  public void setInlineResponse4xx301Success(Boolean inlineResponse4xx301Success) {
    this.inlineResponse4xx301Success = inlineResponse4xx301Success;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse4xx301 inlineResponse4xx301 = (InlineResponse4xx301) o;
    return Objects.equals(this.inlineResponse4xx301Errors, inlineResponse4xx301.inlineResponse4xx301Errors) &&
        Objects.equals(this.inlineResponse4xx301Messages, inlineResponse4xx301.inlineResponse4xx301Messages) &&
        Objects.equals(this.inlineResponse4xx301Result, inlineResponse4xx301.inlineResponse4xx301Result) &&
        Objects.equals(this.inlineResponse4xx301Success, inlineResponse4xx301.inlineResponse4xx301Success) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inlineResponse4xx301Errors, inlineResponse4xx301Messages, inlineResponse4xx301Result, inlineResponse4xx301Success, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse4xx301 {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    inlineResponse4xx301Errors: ").append(toIndentedString(inlineResponse4xx301Errors)).append("\n");
    sb.append("    inlineResponse4xx301Messages: ").append(toIndentedString(inlineResponse4xx301Messages)).append("\n");
    sb.append("    inlineResponse4xx301Result: ").append(toIndentedString(inlineResponse4xx301Result)).append("\n");
    sb.append("    inlineResponse4xx301Success: ").append(toIndentedString(inlineResponse4xx301Success)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
