/*
 * Cloudflare API
 * Interact with Cloudflare's products and services via the Cloudflare API. For more information on how to create and troubleshoot API tokens, refer to our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).  Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse20080ResultSummary0
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-22T14:44:19.166727222+09:00[Asia/Tokyo]")
public class InlineResponse20080ResultSummary0 {
  @SerializedName("HTTP/1.x")
  private String htTP1X = null;

  @SerializedName("HTTP/2")
  private String htTP2 = null;

  @SerializedName("HTTP/3")
  private String htTP3 = null;

  public InlineResponse20080ResultSummary0 htTP1X(String htTP1X) {
    this.htTP1X = htTP1X;
    return this;
  }

   /**
   * Get htTP1X
   * @return htTP1X
  **/
  @Schema(example = "1", required = true, description = "")
  public String getHtTP1X() {
    return htTP1X;
  }

  public void setHtTP1X(String htTP1X) {
    this.htTP1X = htTP1X;
  }

  public InlineResponse20080ResultSummary0 htTP2(String htTP2) {
    this.htTP2 = htTP2;
    return this;
  }

   /**
   * Get htTP2
   * @return htTP2
  **/
  @Schema(example = "39", required = true, description = "")
  public String getHtTP2() {
    return htTP2;
  }

  public void setHtTP2(String htTP2) {
    this.htTP2 = htTP2;
  }

  public InlineResponse20080ResultSummary0 htTP3(String htTP3) {
    this.htTP3 = htTP3;
    return this;
  }

   /**
   * Get htTP3
   * @return htTP3
  **/
  @Schema(example = "60", required = true, description = "")
  public String getHtTP3() {
    return htTP3;
  }

  public void setHtTP3(String htTP3) {
    this.htTP3 = htTP3;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20080ResultSummary0 inlineResponse20080ResultSummary0 = (InlineResponse20080ResultSummary0) o;
    return Objects.equals(this.htTP1X, inlineResponse20080ResultSummary0.htTP1X) &&
        Objects.equals(this.htTP2, inlineResponse20080ResultSummary0.htTP2) &&
        Objects.equals(this.htTP3, inlineResponse20080ResultSummary0.htTP3);
  }

  @Override
  public int hashCode() {
    return Objects.hash(htTP1X, htTP2, htTP3);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20080ResultSummary0 {\n");
    
    sb.append("    htTP1X: ").append(toIndentedString(htTP1X)).append("\n");
    sb.append("    htTP2: ").append(toIndentedString(htTP2)).append("\n");
    sb.append("    htTP3: ").append(toIndentedString(htTP3)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
