/*
 * Cloudflare API
 * Interact with Cloudflare's products and services via the Cloudflare API. For more information on how to create and troubleshoot API tokens, refer to our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).  Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * InlineResponse20041ResultTop0
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-22T13:40:27.702461541+09:00[Asia/Tokyo]")
public class InlineResponse20041ResultTop0 {
  @SerializedName("originCountryAlpha2")
  private String originCountryAlpha2 = null;

  @SerializedName("originCountryName")
  private String originCountryName = null;

  @SerializedName("rank")
  private Integer rank = null;

  @SerializedName("value")
  private String value = null;

  public InlineResponse20041ResultTop0 originCountryAlpha2(String originCountryAlpha2) {
    this.originCountryAlpha2 = originCountryAlpha2;
    return this;
  }

   /**
   * Get originCountryAlpha2
   * @return originCountryAlpha2
  **/
  @Schema(example = "US", required = true, description = "")
  public String getOriginCountryAlpha2() {
    return originCountryAlpha2;
  }

  public void setOriginCountryAlpha2(String originCountryAlpha2) {
    this.originCountryAlpha2 = originCountryAlpha2;
  }

  public InlineResponse20041ResultTop0 originCountryName(String originCountryName) {
    this.originCountryName = originCountryName;
    return this;
  }

   /**
   * Get originCountryName
   * @return originCountryName
  **/
  @Schema(example = "United States", required = true, description = "")
  public String getOriginCountryName() {
    return originCountryName;
  }

  public void setOriginCountryName(String originCountryName) {
    this.originCountryName = originCountryName;
  }

  public InlineResponse20041ResultTop0 rank(Integer rank) {
    this.rank = rank;
    return this;
  }

   /**
   * Get rank
   * @return rank
  **/
  @Schema(example = "1", required = true, description = "")
  public Integer getRank() {
    return rank;
  }

  public void setRank(Integer rank) {
    this.rank = rank;
  }

  public InlineResponse20041ResultTop0 value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @Schema(example = "0.73996", required = true, description = "")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse20041ResultTop0 inlineResponse20041ResultTop0 = (InlineResponse20041ResultTop0) o;
    return Objects.equals(this.originCountryAlpha2, inlineResponse20041ResultTop0.originCountryAlpha2) &&
        Objects.equals(this.originCountryName, inlineResponse20041ResultTop0.originCountryName) &&
        Objects.equals(this.rank, inlineResponse20041ResultTop0.rank) &&
        Objects.equals(this.value, inlineResponse20041ResultTop0.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(originCountryAlpha2, originCountryName, rank, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse20041ResultTop0 {\n");
    
    sb.append("    originCountryAlpha2: ").append(toIndentedString(originCountryAlpha2)).append("\n");
    sb.append("    originCountryName: ").append(toIndentedString(originCountryName)).append("\n");
    sb.append("    rank: ").append(toIndentedString(rank)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
