/*
 * Cloudflare API
 * Interact with Cloudflare's products and services via the Cloudflare API. For more information on how to create and troubleshoot API tokens, refer to our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).  Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.MobileRedirectValue;
import io.swagger.client.model.SchemasBase;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * Automatically redirect visitors on mobile devices to a mobile-optimized subdomain. Refer to [Understanding Cloudflare Mobile Redirect](https://support.cloudflare.com/hc/articles/200168336) for more information.
 */
@Schema(description = "Automatically redirect visitors on mobile devices to a mobile-optimized subdomain. Refer to [Understanding Cloudflare Mobile Redirect](https://support.cloudflare.com/hc/articles/200168336) for more information.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-22T14:44:19.166727222+09:00[Asia/Tokyo]")
public class MobileRedirect extends SchemasBase implements Setting {
  @SerializedName("id")
  private String mobileRedirectId = null;

  @SerializedName("value")
  private MobileRedirectValue mobileRedirectValue = null;

  public MobileRedirect mobileRedirectId(String mobileRedirectId) {
    this.mobileRedirectId = mobileRedirectId;
    return this;
  }

   /**
   * Identifier of the zone setting.
   * @return mobileRedirectId
  **/
  @Schema(example = "mobile_redirect", description = "Identifier of the zone setting.")
  public String getMobileRedirectId() {
    return mobileRedirectId;
  }

  public void setMobileRedirectId(String mobileRedirectId) {
    this.mobileRedirectId = mobileRedirectId;
  }

  public MobileRedirect mobileRedirectValue(MobileRedirectValue mobileRedirectValue) {
    this.mobileRedirectValue = mobileRedirectValue;
    return this;
  }

   /**
   * Get mobileRedirectValue
   * @return mobileRedirectValue
  **/
  @Schema(description = "")
  public MobileRedirectValue getMobileRedirectValue() {
    return mobileRedirectValue;
  }

  public void setMobileRedirectValue(MobileRedirectValue mobileRedirectValue) {
    this.mobileRedirectValue = mobileRedirectValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MobileRedirect mobileRedirect = (MobileRedirect) o;
    return Objects.equals(this.mobileRedirectId, mobileRedirect.mobileRedirectId) &&
        Objects.equals(this.mobileRedirectValue, mobileRedirect.mobileRedirectValue) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mobileRedirectId, mobileRedirectValue, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MobileRedirect {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    mobileRedirectId: ").append(toIndentedString(mobileRedirectId)).append("\n");
    sb.append("    mobileRedirectValue: ").append(toIndentedString(mobileRedirectValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
