/*
 * Cloudflare API
 * Interact with Cloudflare's products and services via the Cloudflare API. For more information on how to create and troubleshoot API tokens, refer to our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).  Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.UpdatePredefinedProfileEntries;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
/**
 * UpdatePredefinedProfile
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-22T14:44:19.166727222+09:00[Asia/Tokyo]")
public class UpdatePredefinedProfile {
  @SerializedName("allowed_match_count")
  private BigDecimal allowedMatchCount = null;

  @SerializedName("entries")
  private List<UpdatePredefinedProfileEntries> entries = null;

  public UpdatePredefinedProfile allowedMatchCount(BigDecimal allowedMatchCount) {
    this.allowedMatchCount = allowedMatchCount;
    return this;
  }

   /**
   * Get allowedMatchCount
   * @return allowedMatchCount
  **/
  @Schema(description = "")
  public BigDecimal getAllowedMatchCount() {
    return allowedMatchCount;
  }

  public void setAllowedMatchCount(BigDecimal allowedMatchCount) {
    this.allowedMatchCount = allowedMatchCount;
  }

  public UpdatePredefinedProfile entries(List<UpdatePredefinedProfileEntries> entries) {
    this.entries = entries;
    return this;
  }

  public UpdatePredefinedProfile addEntriesItem(UpdatePredefinedProfileEntries entriesItem) {
    if (this.entries == null) {
      this.entries = new ArrayList<UpdatePredefinedProfileEntries>();
    }
    this.entries.add(entriesItem);
    return this;
  }

   /**
   * The entries for this profile.
   * @return entries
  **/
  @Schema(description = "The entries for this profile.")
  public List<UpdatePredefinedProfileEntries> getEntries() {
    return entries;
  }

  public void setEntries(List<UpdatePredefinedProfileEntries> entries) {
    this.entries = entries;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdatePredefinedProfile updatePredefinedProfile = (UpdatePredefinedProfile) o;
    return Objects.equals(this.allowedMatchCount, updatePredefinedProfile.allowedMatchCount) &&
        Objects.equals(this.entries, updatePredefinedProfile.entries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allowedMatchCount, entries);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdatePredefinedProfile {\n");
    
    sb.append("    allowedMatchCount: ").append(toIndentedString(allowedMatchCount)).append("\n");
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
