/*
 * Cloudflare API
 * Interact with Cloudflare's products and services via the Cloudflare API. For more information on how to create and troubleshoot API tokens, refer to our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).  Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.BundleMethod;
import io.swagger.client.model.CustomCertificateComponentsSchemasType;
import io.swagger.client.model.GeoRestrictions;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ZoneIdentifierCustomCertificatesBody
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-02-22T14:44:19.166727222+09:00[Asia/Tokyo]")
public class ZoneIdentifierCustomCertificatesBody {
  @SerializedName("bundle_method")
  private BundleMethod bundleMethod = null;

  @SerializedName("certificate")
  private String certificate = null;

  @SerializedName("geo_restrictions")
  private GeoRestrictions geoRestrictions = null;

  @SerializedName("policy")
  private String policy = null;

  @SerializedName("private_key")
  private String privateKey = null;

  @SerializedName("type")
  private CustomCertificateComponentsSchemasType type = null;

  public ZoneIdentifierCustomCertificatesBody bundleMethod(BundleMethod bundleMethod) {
    this.bundleMethod = bundleMethod;
    return this;
  }

   /**
   * Get bundleMethod
   * @return bundleMethod
  **/
  @Schema(description = "")
  public BundleMethod getBundleMethod() {
    return bundleMethod;
  }

  public void setBundleMethod(BundleMethod bundleMethod) {
    this.bundleMethod = bundleMethod;
  }

  public ZoneIdentifierCustomCertificatesBody certificate(String certificate) {
    this.certificate = certificate;
    return this;
  }

   /**
   * Get certificate
   * @return certificate
  **/
  @Schema(required = true, description = "")
  public String getCertificate() {
    return certificate;
  }

  public void setCertificate(String certificate) {
    this.certificate = certificate;
  }

  public ZoneIdentifierCustomCertificatesBody geoRestrictions(GeoRestrictions geoRestrictions) {
    this.geoRestrictions = geoRestrictions;
    return this;
  }

   /**
   * Get geoRestrictions
   * @return geoRestrictions
  **/
  @Schema(description = "")
  public GeoRestrictions getGeoRestrictions() {
    return geoRestrictions;
  }

  public void setGeoRestrictions(GeoRestrictions geoRestrictions) {
    this.geoRestrictions = geoRestrictions;
  }

  public ZoneIdentifierCustomCertificatesBody policy(String policy) {
    this.policy = policy;
    return this;
  }

   /**
   * Get policy
   * @return policy
  **/
  @Schema(description = "")
  public String getPolicy() {
    return policy;
  }

  public void setPolicy(String policy) {
    this.policy = policy;
  }

  public ZoneIdentifierCustomCertificatesBody privateKey(String privateKey) {
    this.privateKey = privateKey;
    return this;
  }

   /**
   * Get privateKey
   * @return privateKey
  **/
  @Schema(required = true, description = "")
  public String getPrivateKey() {
    return privateKey;
  }

  public void setPrivateKey(String privateKey) {
    this.privateKey = privateKey;
  }

  public ZoneIdentifierCustomCertificatesBody type(CustomCertificateComponentsSchemasType type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @Schema(description = "")
  public CustomCertificateComponentsSchemasType getType() {
    return type;
  }

  public void setType(CustomCertificateComponentsSchemasType type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ZoneIdentifierCustomCertificatesBody zoneIdentifierCustomCertificatesBody = (ZoneIdentifierCustomCertificatesBody) o;
    return Objects.equals(this.bundleMethod, zoneIdentifierCustomCertificatesBody.bundleMethod) &&
        Objects.equals(this.certificate, zoneIdentifierCustomCertificatesBody.certificate) &&
        Objects.equals(this.geoRestrictions, zoneIdentifierCustomCertificatesBody.geoRestrictions) &&
        Objects.equals(this.policy, zoneIdentifierCustomCertificatesBody.policy) &&
        Objects.equals(this.privateKey, zoneIdentifierCustomCertificatesBody.privateKey) &&
        Objects.equals(this.type, zoneIdentifierCustomCertificatesBody.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bundleMethod, certificate, geoRestrictions, policy, privateKey, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ZoneIdentifierCustomCertificatesBody {\n");
    
    sb.append("    bundleMethod: ").append(toIndentedString(bundleMethod)).append("\n");
    sb.append("    certificate: ").append(toIndentedString(certificate)).append("\n");
    sb.append("    geoRestrictions: ").append(toIndentedString(geoRestrictions)).append("\n");
    sb.append("    policy: ").append(toIndentedString(policy)).append("\n");
    sb.append("    privateKey: ").append(toIndentedString(privateKey)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
