/*
 * Cloudflare API
 * Interact with Cloudflare's products and services via the Cloudflare API. For more information on how to create and troubleshoot API tokens, refer to our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).  Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.InlineResponse4xx319;
import io.swagger.client.model.SingleUserResponse;
import io.swagger.client.model.UserBody;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for UserApi
 */
@Ignore
public class UserApiTest {

    private final UserApi api = new UserApi();

    /**
     * Edit User
     *
     * Edit part of your user details.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userEditUserTest() throws Exception {
        UserBody body = null;
        SingleUserResponse response = api.userEditUser(body);

        // TODO: test validations
    }
    /**
     * User Details
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void userUserDetailsTest() throws Exception {
        SingleUserResponse response = api.userUserDetails();

        // TODO: test validations
    }
}
