/*
 * Cloudflare API
 * Interact with Cloudflare's products and services via the Cloudflare API. For more information on how to create and troubleshoot API tokens, refer to our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).  Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).
 *
 * OpenAPI spec version: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.DeploymentsListResponse;
import io.swagger.client.model.DeploymentsSingleResponse;
import io.swagger.client.model.InlineResponse4xx195;
import io.swagger.client.model.InlineResponse4xx196;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for WorkerDeploymentsApi
 */
@Ignore
public class WorkerDeploymentsApiTest {

    private final WorkerDeploymentsApi api = new WorkerDeploymentsApi();

    /**
     * Get Deployment Detail
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void workerDeploymentsGetDeploymentDetailTest() throws Exception {
        String deploymentIdentifier = null;
        String scriptIdentifier = null;
        String accountIdentifier = null;
        DeploymentsSingleResponse response = api.workerDeploymentsGetDeploymentDetail(deploymentIdentifier, scriptIdentifier, accountIdentifier);

        // TODO: test validations
    }
    /**
     * List Deployments
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void workerDeploymentsListDeploymentsTest() throws Exception {
        String scriptIdentifier = null;
        String accountIdentifier = null;
        DeploymentsListResponse response = api.workerDeploymentsListDeployments(scriptIdentifier, accountIdentifier);

        // TODO: test validations
    }
}
